blueprint:
  name: Slow Device Startup
  description: An event-based startup sequence
  domain: script
  author: Richard Berg
  source_url: https://github.com/richard-berg/hass-yaml-rberg/blob/main/blueprints/script/richardberg/slow_device_startup.yaml
  input:
    media_entity:
      name: Media Entity
      selector:
        entity:
          filter:
            domain: media_player
    remote_entity:
      name: Remote Entity
      selector:
        entity:
          filter:
            domain: remote
    startup_commands:
      name: Startup Commands
      selector:
        text:
          multiple: true
    repeat_turnon_after:
      name: Initial Timeout
      description: If the device hasn't turned on after this many seconds, send another turn-on command
      default: 30
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: seconds
          mode: box
sequence:
  - action: remote.turn_on
    target:
      entity_id: !input remote_entity
  - parallel:
      - sequence:
          # main startup sequence
          - if:
              - condition: state
                entity_id: !input media_entity
                state:
                  - "off"
                  - "unavailable"
                  - "unknown"
            then:
              - wait_for_trigger:
                  - trigger: state
                    entity_id: !input media_entity
                    not_to:
                      - "off"
                      - "unavailable"
                      - "unknown"
          - repeat:
              for_each: !input startup_commands
              sequence:
                - action: remote.send_command
                  data:
                    num_repeats: 1
                    delay_secs: 0.7
                    hold_secs: 0
                    command: "{{ repeat.item }}"
                  target:
                    entity_id: !input remote_entity
      - sequence:
          # handle cases where initial turn_on command was dropped, e.g. because
          # the device was in the middle of shutting down
          - if:
              - condition: state
                entity_id: !input media_entity
                state:
                  - "off"
                  - "unavailable"
                  - "unknown"
            then:
              - wait_for_trigger:
                  - trigger: state
                    entity_id: !input media_entity
                    not_to:
                      - "off"
                      - "unavailable"
                      - "unknown"
                timeout:
                  seconds: !input repeat_turnon_after
              - action: remote.turn_on
                target:
                  entity_id: !input remote_entity
